name: Android CI

on:
  push:
    branches: [ feature/ci_test ]
  pull_request:
    branches: [ feature/ci_test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assembleRelease
    - name: Distribute to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: surya.is.vel-gmail.com/ActionEx
        token: ${{ secrets.AC_TOKEN }}
        file: app/build/outputs/apk/release/app-release.apk
        debug: false
